[project]
docs_dir="docs"
site_name="Dev Handbook"

[project.theme]
features = [
  "navigation.tabs",
  "navigation.tabs.sticky",
  "navigation.sections",
#  "navigation.indexes",
  "navigation.top",
  "navigation.prune"
]

[project.markdown_extensions.abbr]

[project.markdown_extensions.admonition]

# Code blocks
# https://zensical.org/docs/authoring/code-blocks/#configuration
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.snippets]
[project.markdown_extensions.pymdownx.superfences]
